services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  lottiefiles-pwa:
